alias ls='eza --color=always --group-directories-first --icons'
alias lf='eza --color=always --group-directories-first --icons -f'
alias ld='eza --color=always --group-directories-first --icons -D'
alias ll='eza --color=always  -l --git --icons -a'
alias lt='eza --color=always --tree --level=1 --icons'
alias lth='eza --color=always --tree --level=1 --icons -a'
alias ltt='eza --color=always --tree --level=2 --icons'
alias ltth='eza --color=always --tree --level=2 --icons -a'
alias lsh='eza --color=always -a --group-directories-first --icons --git'
alias lshf='eza --color=always -a --group-directories-first --icons -f --git --show-symlinks'
alias lshd='eza -a -a --group-directories-first --icons -D --git --show-symlinks'
